### ISSUE TITLE
Where to close the Database?

### ISSUE THREAD

**Issue by Kulitech** [Glyphack/go-graphql-hackernews#4]
Hi! Where can I `defer DB.Close( )`?

**Comment by Glyphack** [comment]
Hello, You can have a CloseDB function in [mysql.go](https://github.com/Glyphack/graphql-golang/blob/master/internal/pkg/db/mysql/mysql.go) file that closes the database and defer this function after this line in server code https://github.com/Glyphack/graphql-golang/blob/master/server.go#L30
